### ISSUE TITLE
Azure Pipelines integration

### ISSUE THREAD

**Issue by Bjego** [microsoft/infersharp#19]
Good Morning,
are there any plans to integrate your tool with Azure Pipelines as well?

I would love to use it in my pull requests for analysis! And it would be great, if a plugin could decorate a pull request with comments on the issued files / lines (as SonarCloud does).

This relates to https://devblogs.microsoft.com/dotnet/infer-interprocedural-memory-safety-analysis-for-c/#comment-8145, but for tracking reasons I assume it's better to flag up a feature request here.

**Comment by matjin** [comment]
Thanks for posting interest in this! We're looking at all feature requests from the community and will prioritize next steps based on popularity.

**Comment by josundt** [comment]
+1 vote

**Comment by deepumi** [comment]
+1 vote for Azure Devops!
