### ISSUE TITLE
Binary Releases?

### ISSUE THREAD

**Issue by TomMD** [microsoft/infersharp#21]
Building infer is hard - it requires lots of disk space and time.  InferSharp presumably isn't drastically different.  Do you have/plan on making binary releases?

**Comment by matjin** [comment]
We do have a [docker image](https://github.com/microsoft/infersharp/blob/main/README.md#docker-image) with prebuilt with everything: docker pull mcr.microsoft.com/infersharp:latest

Additionally, please keep in mind that InferSharp uses the [Java version of Infer](https://github.com/microsoft/infersharp/blob/main/CONTRIBUTING.md#installation-and-build), not clang (the former being significantly faster to build).

cd infer
./build-infer.sh ./autogen.sh
./build-infer.sh java
./autogen.sh
sudo make install

**Comment by xinshiMSFT** [comment]
Binary release available. https://github.com/microsoft/infersharp/releases
