### ISSUE TITLE
Provide SARIF output

### ISSUE THREAD

**Issue by paulomorgado** [microsoft/infersharp#23]
The [Static Analysis Results Interchange Format (SARIF)](http://sarifweb.azurewebsites.net/) has been [approved](https://www.oasis-open.org/news/announcements/static-analysis-results-interchange-format-sarif-v2-1-0-is-approved-as-an-oasis-s) as an [OASIS](https://www.oasis-open.org/) standard.

**Comment by xinshiMSFT** [comment]
https://github.com/facebook/infer/pull/1487

**Comment by xinshiMSFT** [comment]
SARIF support in [v1.2](https://github.com/microsoft/infersharp/releases/tag/v1.2)
