### ISSUE TITLE
Unable to start 

### ISSUE THREAD

**Issue by aleksandrsmyk** [microsoft/infersharp#25]
When executing :
sh run_infersharp.sh Examples output

I got :
sh: run_infersharp.sh: No such file or directory

Could you suggest any options to fix it?

**Comment by xinshiMSFT** [comment]
After you've pulled the image, start an interactive container:
``
docker run -it mcr.microsoft.com/infersharp:latest
``

run_infersharp.sh should be under /app/:
![Untitled](https://user-images.githubusercontent.com/7873492/103044041-e2768980-4533-11eb-9c0a-ccf42c6f6d47.png)

**Comment by vswathidev** [comment]
sh: 0: Can't open run_infersharp.sh

with azure pipeline task  given in  .build/azure-pipelines-example.yml

**Comment by ethanturk** [comment]
I'm having the same problem with the Azure Pipeline task example. I can run the example in a local container, though.

**Comment by ethanturk** [comment]
I put a 'ls' into my script run. Here is the output at the base folder (on our ADO build agents) where the example tries to run the script. Locally, I get a completely different listing. I'm still debugging this issue.

CODEOWNERS
azure-pipelines-ect-test.yml
docs
lib
readme.md
src
tools
sh: 0: Can't open run_infersharp.sh
##[error]Bash exited with code '127'.

**Comment by xinshiMSFT** [comment]
Hi @vswathidev, @ethanturk, it seems that your Azure Pipelines were not running in [container mode](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops), but rather directly on the host. Can you double check if the container section of your pipelines looks like this?
```
pool:
  vmImage: 'ubuntu-20.04'
container:
  image: mcr.microsoft.com/infersharp:latest
```
[This](https://dev.azure.com/ms/infersharp/_build/results?buildId=134974&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86) is one of the test run results on Azure Pipelines using .build/azure-pipelines-example.yml.

**Comment by ethanturk** [comment]
Here is the addition to my pipeline:

  # Run Infer#
  - job: RunInferSharp
    dependsOn: 'BuildSolution'
    pool:
      vmImage: 'ubuntu-20.04'
    container:
      image: mcr.microsoft.com/infersharp:latest

    steps:
      # Download binaries
      - task: DownloadBuildArtifacts@0
        displayName: 'Download binaries'
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'inferinput'
          downloadPath: '$(System.ArtifactsDirectory)'

      - script: |
          sh run_infersharp.sh $(System.ArtifactsDirectory) output
        displayName: 'Run Infer# analysis'

      - script: cat $(Build.SourcesDirectory)/infer-out/filtered_bugs.txt
        displayName: 'Infer# analysis result'

**Comment by xinshiMSFT** [comment]
Thanks for the additional info! I think I know where it could have gone wrong. Let me get the fix ready.

**Comment by xinshiMSFT** [comment]
So the problem is that _run_infersharp.sh_ needs to be present on the host first in order to run in a container. You can refer to the PR linked above for the updated instructions. I think it should resolve the issue. Please let me know otherwise. Thanks!

**Comment by ethanturk** [comment]
I saw the PR. It seems to have resolved the issue on my end, yes. Thanks for the quick response.
